### ISSUE TITLE
Performance Optimization with SIMD.js: Any chance?

### ISSUE THREAD

**Issue by fpietrosanti** [dchest/scrypt-async-js#13]
Solar Designer said on Cryptography@randombit.net mailing list that yescrypt-lite (successor of scrypt) will be implemented in js this summer with a GSoc using SMID.js:
https://hacks.mozilla.org/2014/10/introducing-simd-js/

I'm wondering if also scrypt-async-js would not benefit from the same approach?

**Comment by dchest** [comment]
Yes, it would most likely benefit from it, however I don't think there's a consensus that SIMD.js will ever be standardized. Will see what happens, so far it would be a wasted effort to implement it.

**Comment by fpietrosanti** [comment]
@dchest Do you think that, on the basis of scrypt-async-js, would be reasonable to make a yescrypt-lite implementation (that, as far as i understood in my humble surface understanding of crypto share similar concept) ?

**Comment by dchest** [comment]
@fpietrosanti yes, it would be reasonable.
