### ISSUE TITLE
Bring back SauceLabs

### ISSUE THREAD

**Issue by grempe** [dchest/scrypt-async-js#29]
Page not found:
https://saucelabs.com/u/dchest

**Comment by dchest** [comment]
Thanks, they removed free accounts, so I removed them.

**Comment by evilaliv3** [comment]
@dchest they have not removed free accounts.

it is just that you probably registered a temporary free account.

there are instead "open source" accounts that are free forevah!

https://saucelabs.com/open-source

**Comment by dchest** [comment]
Oh, I see, thanks! I'll take care of it later.

**Comment by dchest** [comment]
I brought it back, however I don't think it actually works, judging by screencasts from SauceLabs, and probably didn't work before: when I try to run unittests.html locally, I get:

```
unittests-bundle.js:1899 Uncaught ReferenceError: describe is not defined
```

@evilaliv3 any ideas why?

**Comment by evilaliv3** [comment]
how are you running the unit tests?

i guess using npm or node directly.

the tests are instead meant to be runned inside the browser pointing it to the directory with the HTML or by using the mocha binary.

(https://stackoverflow.com/questions/28400459/referenceerror-describe-is-not-defined-nodejs)

**Comment by dchest** [comment]
I opened `unittests.html` in browser. Sauce Labs does the same here: https://saucelabs.com/tests/21f133eb29db4c799451055c3d11bc32 (see screenshot or screencast), although you can't see console output.

**Comment by dchest** [comment]
Yay!

<img width="807" alt="screen shot 2016-09-06 at 12 08 32" src="https://cloud.githubusercontent.com/assets/52677/18269909/aef1d0b2-742a-11e6-9c2f-8460826162b6.png">


Thank you, guys.

**Comment by grempe** [comment]
Great
