### ISSUE TITLE
Idea: Utilize SubtleCrypto when webcrypto is supported by the platform

### ISSUE THREAD

**Issue by vflyson** [dchest/scrypt-async-js#36]
I'd like to ask about the possibility of making `scrypt-async-js` to be taking advantage of `window.crypto` when it's available for calculating SHA-256, and possibly performing other cryptographic calculations for the sake of speeding up the performance on newer devices.

Related links:
https://www.w3.org/TR/WebCryptoAPI/
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto
https://github.com/diafygi/webcrypto-examples

Thank you.

**Comment by dchest** [comment]
Please see https://github.com/dchest/scrypt-async-js/issues/9#issuecomment-98620761

**Comment by vflyson** [comment]
My apologies, have no idea how I've missed that issue. The reasoning for not implementing webcrypto makes total sense, thank you for pointing me in the right direction.

**Comment by dchest** [comment]
No worries!
