### ISSUE TITLE
What is the best value of R parameter?

### ISSUE THREAD

**Issue by felgarte** [dchest/scrypt-async-js#39]
Most of the examples the value is 8, but when I decrease the number ('till 1) the execution time it goes down considerably.

Can someone explain to me what incidence R has and what is the lowest number to use it?

Thanks!

**Comment by dchest** [comment]
The best value for today's and near future computers is 8.

See: https://github.com/dchest/scrypt-async-js/issues/23#issuecomment-190666894

Explanation: https://blog.filippo.io/the-scrypt-parameters/
