### ISSUE TITLE
synchronous version?

### ISSUE THREAD

**Issue by fruiz500** [dchest/scrypt-async-js#4]
I really like this code, but I want to use it in a program where the KDF needs to be called several times for different strings. Waiting is a plus, since I want to encourage users to use high-entropy passwords, and I add rounds of KDF for low entropy.

Is there a way to use your function synchronously, without callbacks?

**Comment by dchest** [comment]
Answered here: https://github.com/dchest/tweetnacl-js/issues/68

FYI, you can wait even async functions — just disable any other actions (for example, in `demo.html` I disable button until the function is done).
