### ISSUE TITLE
Scrypt throws error if the key.length > 64 when the data structure does not support .push

### ISSUE THREAD

**Issue by TotalTechGeek** [dchest/scrypt-async-js#42]
Steps to reproduce - 

1) Create a key greater than length 64. 
2) Use a structure that doesn't support .push (like Buffer), 
ex.
```js
let key = Buffer.from('0'.repeat(65))
```
3) run scrypt

---- 

The short term fix is to convert to a structure that does support the .push operation. 

I will be submitting a PR

**Comment by TotalTechGeek** [comment]
You're in good company though: ricmoo's scrypt-js also has the same bug.

**Comment by dchest** [comment]
You're right, thanks! The error is here: https://github.com/dchest/scrypt-async-js/blob/master/scrypt-async.js#L157  `SHA256(password)` expects password to be an `Array`, but if password is `Uint8Array`, it obviously won't work. I'll wait for you PR.
