### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by jo** [dchest/scrypt-async-js#5]
I need this in npm.

Would you like me to add a `package.json` and make a pull so that you can publish the package? Or do you prefer not to maintain the npm package, in which case I would publish a fork by myself?

Thanks for your great work!

**Comment by dchest** [comment]
Sure, make do a pull request, and I'll publish it. Thanks!

**Comment by jo** [comment]
here it is: #6

**Comment by dchest** [comment]
Thanks, published!

**Comment by jo** [comment]
Thank you!
