### ISSUE TITLE
Optimize scrypt performance working over multiple cores with multiple web workers

### ISSUE THREAD

**Issue by fpietrosanti** [dchest/scrypt-async-js#7]
Hi,

is it possible, after having estimated the numbers of CPU cores of a browser (using https://github.com/oftn/core-estimator), to use scrypt-async-js in a way that will split it's CPU load across multiple webworkers (so, multiple CPU cores) ?

Is the algorithm logic supporting somehow this optimization / implementation?

**Comment by dchest** [comment]
Hi,

There is no way to split computation into multiple cores as it is (that's one of the points of `scrypt`), but there's a parallelization parameter (*p*) in the original algorithm, which enables something like this, however it's not usually used (even reference computes it sequentially), and `scrypt-async-js` doesn't support it (`p=1` is fixed) for simplicity.
